---
name: Main
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  WORKSPACE: ${{ github.workspace }}
  TARGET_ARCH: aarch64
  TARGET: arm64
  META: ${{ env.WORKSPACE }}/.cirrus-ci/scripts/test/meta/main-${{ env.TARGET_ARCH }}-run.sh
    #ARTIFACT_DEST: artifact/${FBSD_BRANCH}/${GIT_COMMIT}/${TARGET}/${TARGET_ARCH}
    #CIRRUS_CLONE_DEPTH: 1
    #MAKEOBJDIRPREFIX: /tmp/obj
    #MAKECONF: /dev/null
    #SRCCONF: /dev/null
    #JFLAG: 8
    #EXTRA_FLAGS:
    #FBSD_BRANCH: $CIRRUS_BRANCH
    #GIT_COMMIT: $CIRRUS_CHANGE_IN_REPO
    #JOB_NAME: $CIRRUS_TASK_NAME
    #WITH_LIB32: 0
    #WITH_DEBUG: 0
    #WITH_TESTS: 0

jobs:
  deploy:
    name: Run FreeBSD Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y curl qemu qemu-kvm qemu-system qemu-efi u-boot-qemu
      - name: Check ENV
        run: echo $WORKSPACE
      - name: Check Current Working Directory
        run: pwd
      - name: List files
        run: ls -la
      - name: Fetch Artifact
        run: sh -ex .cirrus-ci/scripts/fetch-artifact.sh
      - name: Run Test
        run: |
          cd ${WORKSPACE}
          ls -la ${WORKSPACE}/work
          sh -ex .cirrus-ci/scripts/test/run-tests.sh
