---
name: Main
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  WORKSPACE: ${{ github.workspace }}

jobs:
  deploy:
    name: Run FreeBSD Testing
    env:
      USE_TEST_SUBR: |
        disable-disks-tests.sh
        disable-dtrace-tests.sh
        disable-zfs-tests.sh
        disable-notyet-tests.sh
        run-kyua.sh
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV
        run: |
          echo 'TARGET_ARCH=aarch64' >> $GITHUB_ENV
          #TARGET: arm64
          #QEMU_ARCH: $TARGET_ARCH
          #QEMU_MACHINE: virt
          #QEMU_EXTRA_PARAM: -bios /usr/lib/u-boot/qemu_arm64/u-boot.bin -cpu cortex-a57
          #USE_QEMU: 1
    #ARTIFACT_DEST: artifact/${FBSD_BRANCH}/${GIT_COMMIT}/${TARGET}/${TARGET_ARCH}
    #CIRRUS_CLONE_DEPTH: 1
    #MAKEOBJDIRPREFIX: /tmp/obj
    #MAKECONF: /dev/null
    #SRCCONF: /dev/null
    #JFLAG: 8
    #EXTRA_FLAGS:
    #FBSD_BRANCH: $CIRRUS_BRANCH
    #GIT_COMMIT: $CIRRUS_CHANGE_IN_REPO
    #JOB_NAME: $CIRRUS_TASK_NAME
    #WITH_LIB32: 0
    #WITH_DEBUG: 0
    #WITH_TESTS: 0
      - name: Set Nested ENV
        run: |
          echo 'META=${{ env.WORKSPACE }}/.cirrus-ci/scripts/test/meta/main-${{ env.TARGET_ARCH }}-run.sh' >> $GITHUB_ENV
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y curl qemu qemu-kvm qemu-system qemu-efi u-boot-qemu
      - name: Check ENV
        run: echo ${{ env.META }}
      - name: Fetch Artifact
        run: sh -ex .cirrus-ci/scripts/fetch-artifact.sh
      - name: Run Test
        run: |
          cd ${WORKSPACE}
          ls -la ${WORKSPACE}/work
          sh -ex .cirrus-ci/scripts/test/run-tests.sh
