---
name: Main
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  WORKSPACE: $GITHUB_WORKSPACE

jobs:
  deploy:
    name: Run FreeBSD Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y curl qemu qemu-kvm qemu-system qemu-efi u-boot-qemu
      - name: Check ENV
        run: echo $WORKSPACE
      - name: Fetch Artifact
        run: sh -ex ${WORKSPACE}/.cirrus-ci/scripts/fetch-artifact.sh
