---
name: Main
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  WORKSPACE: ${{ github.workspace }}

jobs:
  deploy:
    name: Run FreeBSD Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV
        run: |
          echo 'TARGET_ARCH=aarch64' >> $GITHUB_ENV
          echo 'META=${{ env.WORKSPACE }}/.cirrus-ci/scripts/test/meta/main-$TARGET_ARCH-run.sh
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://example.lab >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          #TARGET: arm64
          #QEMU_ARCH: $TARGET_ARCH
          #QEMU_MACHINE: virt
          #QEMU_EXTRA_PARAM: -bios /usr/lib/u-boot/qemu_arm64/u-boot.bin -cpu cortex-a57
          #USE_QEMU: 1
          #echo 'USE_TEST_SUBR<<EOF' >> $GITHUB_ENV
          #disable-disks-tests.sh >> $GITHUB_ENV
          #disable-dtrace-tests.sh >> $GITHUB_ENV
          #disable-zfs-tests.sh >> $GITHUB_ENV
          #disable-notyet-tests.sh >> $GITHUB_ENV
          #run-kyua.sh >> $GITHUB_ENV
          #echo 'EOF' >> $GITHUB_ENV
    #ARTIFACT_DEST: artifact/${FBSD_BRANCH}/${GIT_COMMIT}/${TARGET}/${TARGET_ARCH}
    #CIRRUS_CLONE_DEPTH: 1
    #MAKEOBJDIRPREFIX: /tmp/obj
    #MAKECONF: /dev/null
    #SRCCONF: /dev/null
    #JFLAG: 8
    #EXTRA_FLAGS:
    #FBSD_BRANCH: $CIRRUS_BRANCH
    #GIT_COMMIT: $CIRRUS_CHANGE_IN_REPO
    #JOB_NAME: $CIRRUS_TASK_NAME
    #WITH_LIB32: 0
    #WITH_DEBUG: 0
    #WITH_TESTS: 0
      - name: Check nested env calls
        run: |
          echo "${{ env.META }}"
          echo "${{ env.USE_TEST_SUBR }}"
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y curl qemu qemu-kvm qemu-system qemu-efi u-boot-qemu
      - name: Check ENV
        run: echo $WORKSPACE
      - name: Check Current Working Directory
        run: pwd
      - name: List files
        run: ls -la
      - name: Fetch Artifact
        run: sh -ex .cirrus-ci/scripts/fetch-artifact.sh
      - name: Run Test
        run: |
          cd ${WORKSPACE}
          ls -la ${WORKSPACE}/work
          sh -ex .cirrus-ci/scripts/test/run-tests.sh
